### ISSUE TITLE
the installation methods and steps not defined in markdown readme

### ISSUE THREAD

**Issue by Fliw** [microsoft/qlib-server#1]
the readme.md was not completed, is there a other way to install this? there is no documentation to see or read.

**Comment by you-n-g** [comment]
We are in active development. 
The completed version will be released soon. 
You can try to read the docs first https://qlib-server.readthedocs.io/ .

If you encounter any problem, please contact us.

Before try the Online version of Qlib,  you can try the [offline version](https://github.com/microsoft/qlib/) first

**Comment by Fliw** [comment]
thank you

**Comment by you-n-g** [comment]
@Fliw   We've finished the documents now. 
If you have any problems when reading the docs, feel free to contact us.
Otherwise, we'll close this issue later.

**Comment by Fliw** [comment]
okay, thank you ✌🏻 i will close this issue now
